"""Small helpers shared by the generators: Markdown tables, links, role names, headers."""

from __future__ import annotations

from collections.abc import Iterable, Sequence
from pathlib import Path

from isms_as_code import layout
from isms_as_code.ids import control_sort_key
from isms_as_code.loader import ControlGuide, Document, Repository

__all__ = [
    "md_header",
    "hash_header",
    "cell",
    "table",
    "document_link",
    "guide_link",
    "role_title",
    "role_with_holder",
    "sorted_controls",
    "status_label",
]


def md_header(digest: str) -> str:
    return (
        "<!-- Generated by `isms generate` from the ISMS sources -- do not edit by hand. "
        f"Source digest: sha256:{digest} -->\n\n"
    )


def hash_header(digest: str, what: str) -> str:
    return (
        f"# Generated by `isms generate` from {what} -- do not edit by hand.\n"
        f"# Source digest: sha256:{digest}\n"
    )


def cell(text: object) -> str:
    """Escape a value for use inside a GFM table cell; empty cells become an em dash."""
    escaped = str(text).replace("|", "\\|").replace("\n", " ").strip()
    return escaped or "—"


def table(headers: Sequence[str], rows: Iterable[Sequence[object]]) -> str:
    lines = [
        "| " + " | ".join(cell(h) for h in headers) + " |",
        "| " + " | ".join("---" for _ in headers) + " |",
    ]
    for row in rows:
        lines.append("| " + " | ".join(cell(value) for value in row) + " |")
    return "\n".join(lines) + "\n"


def document_link(
    repo: Repository, document: Document, from_dir: Path = layout.GENERATED_DIR
) -> str:
    target = Path(repo.relpath(document.path))
    depth = len(from_dir.parts)
    rel = Path(*([".."] * depth)) / target
    return f"[{document.meta.id}]({rel.as_posix()})"


def guide_link(repo: Repository, guide: ControlGuide, from_dir: Path = layout.GENERATED_DIR) -> str:
    target = Path(repo.relpath(guide.path))
    depth = len(from_dir.parts)
    rel = Path(*([".."] * depth)) / target
    return f"[{guide.meta.control}]({rel.as_posix()})"


def role_title(repo: Repository, key: str) -> str:
    role = repo.roles.by_key().get(key)
    return role.title if role else key


def role_with_holder(repo: Repository, key: str) -> str:
    role = repo.roles.by_key().get(key)
    return f"{role.title} ({role.holder})" if role else key


def sorted_controls(ids: Iterable[str]) -> list[str]:
    return sorted(set(ids), key=control_sort_key)


def status_label(value: object) -> str:
    text = str(getattr(value, "value", value))
    return text.replace("-", " ")
